version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    restart: unless-stopped
  redis:
    image: redis:6-alpine
    container_name: redis
    hostname: redis
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.0
    container_name: keycloak
    hostname: keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth/
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 7777:8080
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
  config-server:
    image: "config-server:latest"
    ports:
      - "8080:8080"
  product-adapter-service:
    image: "product-adapter-service:latest"
    ports:
      - "9082:8080"
    depends_on:
      - registry-service
  product-service:
    image: "product-service:latest"
    ports:
      - "8080"
    depends_on:
      - registry-service
  registry-service:
    image: "registry-service:latest"
    ports:
      - "8761:8761"
    depends_on:
      - config-server
  audit-service:
    image: "audit-service:latest"
    ports:
      - "8080"
    depends_on:
      - registry-service
  spring-cloud-gateway:
    image: "spring-cloud-gateway:latest"
    ports:
      - "8070:8080"
    depends_on:
      - registry-service
volumes:
  mongo-volume: {}
  redis-volume: {}
